name: Daily Stock News

on:
  schedule:
    - cron: "30 23 * 3-10 *" # UTC 23:30 (前一天，台灣時間 7:30) 3月到10月
    - cron: "30 0 * 11-12,1-2 *" # UTC 0:30 (台灣時間 8:30) 11月到2月
  workflow_dispatch: # 保留手動觸發選項

jobs:
  scrape-and-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper and send notifications
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
        run: python stock_news_scraper.py
